language: objective-c
osx_image: xcode8.2
xcode_project: TravisCIDemo.xcodeproj
xcode_scheme: TravisCIDemo

script:
- xctool -project TravisCIDemo.xcodeproj -scheme 'TravisCIDemo' -configuration Release -sdk iphonesimulator -arch i386 build
