language: objective-c
osx_image: xcode8.2
xcode_project: TravisCIDemo.xcodeproj
xcode_scheme: TravisCIDemo

script:
- xctool -project TravisCIDemo.xcodeproj -scheme TravisCIDemo build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
